kind: PersistentVolume
apiVersion: v1
metadata:
  name: jira-datacenter-pv
  labels:
    product: atlassian-jira
    type: datacenter
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs.example.com
    path: /tmp/nfs/jira-datacenter
    readOnly: false
