apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-postgresql-pvc
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
    matchLabels:
      product: postgresql
      stage: canary
      supporting: atlassian-jira
