kind: PersistentVolume
apiVersion: v1
metadata:
  name: jira-server-pv
  labels:
    product: atlassian-jira
    type: server
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/jira-server-pv"
