
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-postgresql-pv
  labels:
    product: postgresql
    stage: canary
    supporting: atlassian-jira
spec:
  storageClassName: hostpath
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/tmp/jira-postgresql-pv"
    type: DirectoryOrCreate
