#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: postgres
#  namespace: jira
#spec:
#  accessModes:
#  - ReadWriteMany
#  storageClassName: "postgres"
#  resources:
#    requests:
#      storage: 5Gi
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  namespace: jira
#  name: postgres
#spec:
#  capacity:
#    storage: 5Gi
#  accessModes:
#  - ReadWriteMany
#  storageClassName: "postgres"
#  hostPath:
#    path: "/var/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
